;(function(ns){
   ns.host="http://192.168.1.34:65380";
   ns.screenHeight=undefined;
   ns.screenWidth=undefined;
   ns.containerMain=undefined;
   ns.router=undefined;
   ns.pathTemplate="src/templ/";
   ns.pathDataConfig="src/data/";
})(this.values||(this.values={}));