({
    //baseUrl:".",
        paths:{
       jquery:"bower/jquery/dist/jquery.min",
       handlebars:"bower/handlebars/handlebars.amd.min",
       hammer:"bower/hammerjs/hammer.min",
       director:"bower/director/build/director.min",
       hashtable:"bower/jshashtable/hashtable",
       promise:"bower/promise-polyfill/promise.min",
       mutationobserver:"bower/MutationObserver-shim/dist/mutationobserver.min",
       values:"src/shared/js/values",
       util01:"src/shared/js/util01",
       component:"src/shared/js/components01",
       componentscroll:"src/components/menu-vertical/componentsMenuVerticalScroll01",
       mousetrap:"bower/mousetrap/mousetrap.min",
       inputmask:"bower/Inputmask/dist/inputmask/inputmask",
       inputmaskdeplib:"bower/Inputmask/dist/inputmask/inputmask.dependencyLib",
       inputmaskdate:"bower/Inputmask/dist/inputmask/inputmask.date.extensions",
       inputmaskext:"bower/Inputmask/dist/inputmask/inputmask.extensions",
       inputmasknum:"bower/Inputmask/dist/inputmask/inputmask.numeric.extensions",
       inputmaskphone:"bower/Inputmask/dist/inputmask/inputmask.phone.extensions",
       inputmaskregex:"bower/Inputmask/dist/inputmask/inputmask.regex.extensions",
       table:"src/components/Table/table01",
       behaviors:"src/shared/js/behaviors",
       behaviors03layout02:"src/shared/js/behaviors03layout02",
       text:"bower/text/text",
       css:"bower/require-css/css.min",
       image:"bower/requirejs-plugins/lib/require/image",
       json:"bower/requirejs-plugins/lib/require/json",
       font:"bower/requirejs-plugins/lib/require/font",
       propertyparser:"bower/requirejs-plugins/lib/require/propertyparser"
    },
     map:{
        "*":{
            css:"bower/require-css/css"
        }
    },
    //appDir:"bower",
    //dir:"dist",
    //modules:[
    //  {name:"main"}
    //],
       shim:{
        "handlebars":{
           exports:"Handlebars"
        },
        "hammer":{
            exports:"Hammer"
        },
        "util01":{
            deps:["values","handlebars","jquery","hammer","promise"],
        },
        "component":{
            deps:["util01","behaviors","behaviors03layout02","promise","mutationobserver"]
        },
        "inputmask":{
            deps:["inputmaskdeplib"]
        },
        "inputmaskdate":{
            deps:["inputmask"]
        },
        "inputmaskext":{
            deps:["inputmask"]
        }, 
        "inputmasknum":{
            deps:["inputmask"]
        },
        "inputmaskphone":{
            deps:["inputmask"]
        },
        "inputmaskregex":{
            deps:["inputmask"]
        },
        "table":{
            deps:["hashtable","mousetrap","inputmask","inputmaskdate",
            "inputmaskext","inputmasknum",
            "inputmaskphone","inputmaskregex"]
        }
    },
    name:"main",
    out:"main-built.js"
})